// Extended comprehensive dummy data for SkillSwap backend
// All models and fields included, with even more variety and relationships
const userid_1 = "68486dbeaa25de31a4d74a8b";
const userid_2 = "68486cbdaa25de31a4d74a77";
const userid_3 = "68480fbc50e067371cfebdf8";
const userid_4 = "68480ee150e067371cfebdf3";
const skillId_1 = "684987fca5cb1a8609a54ca7";
const skillId_2 = "684577126cd32cc6283d1275";
const postId_1 = "68497c72a5cb1a8609a54c80";
const postId_2 = "6849709aa5cb1a8609a54c36"
const postId_3 = "68496ea5a5cb1a8609a54c2e"
const eventId_1 = "684989caa5cb1a8609a54cac";
const eventId_2 = "684989e0a5cb1a8609a54cae"
const communityId_1 = "68498a0ba5cb1a8609a54cb2";
const communityId_2 = "68498a2ea5cb1a8609a54cb4"
module.exports = {
  users: [
    {
      email: "testuser@example.com",
      password: "test1234",
      firstName: "Test",
      lastName: "User",
      username: "testuser",
      gender: "other",
      avatar: "https://randomuser.me/api/portraits/lego/1.jpg",
      banner: "https://picsum.photos/800/200?testuser",
      bio: "Test account for login.",
      about: "This is a test user for API login.",
      skills: [],
      location: { city: "Testville", country: "Testland" },
      contact: {
        email: "testuser@example.com",
        phone: "+10000000000",
        visibility: "public",
      },
      timeZone: "UTC",
      language: "en",
      followers: [],
      following: [],
      blocked: [],
      privacy: { profile: "public" },
      completion: 100,
      badges: [
        { name: "Tester", earnedAt: new Date() }
      ],
      credits: 99,
      devices: [
        {
          deviceId: "devtest",
          ip: "127.0.0.1",
          lastLogin: new Date(),
          active: true,
        }
      ],
    },
    {
      email: "john@example.com",
      password: "Pass123!",
      firstName: "John",
      lastName: "Doe",
      username: "johndoe",
      gender: "male",
      avatar: "https://randomuser.me/api/portraits/men/1.jpg",
      banner: "https://picsum.photos/800/200?1",
      bio: "Web developer and mentor.",
      about: "I love building web apps and teaching others.",
      skills: [skillId_1, skillId_2],
      location: { city: "New York", country: "USA" },
      contact: {
        email: "john@example.com",
        phone: "+1234567890",
        visibility: "public",
      },
      timeZone: "America/New_York",
      language: "en",
      followers: [userid_2, userid_3, userid_4],
      following: [userid_2, userid_4],
      blocked: [userid_1],
      privacy: { profile: "public" },
      // activity: ["ACTIVITY_ID_1", "ACTIVITY_ID_2"],
      // hiddenActivity: ["ACTIVITY_ID_3"],
      completion: 90,
      badges: [
        { name: "Mentor", earnedAt: new Date() },
        { name: "Top Contributor", earnedAt: new Date() },
      ],
      credits: 10,
      devices: [
        {
          deviceId: "dev1",
          ip: "192.168.1.2",
          lastLogin: new Date(),
          active: true,
        },
        {
          deviceId: "dev2",
          ip: "10.0.0.2",
          lastLogin: new Date(),
          active: false,
        },
      ],
    },
    {
      email: "jane@example.com",
      password: "Pass123!",
      firstName: "Jane",
      lastName: "Smith",
      username: "janesmith",
      gender: "female",
      avatar: "https://randomuser.me/api/portraits/women/2.jpg",
      banner: "https://picsum.photos/800/200?2",
      bio: "Guitarist and music teacher.",
      about: "Passionate about music and sharing knowledge.",
      skills: [skillId_1, skillId_2],
      location: { city: "London", country: "UK" },
      contact: {
        email: "jane@example.com",
        phone: "+447911123456",
        visibility: "public",
      },
      timeZone: "Europe/London",
      language: "en",
      followers: [userid_1, userid_3],
      following: [userid_1, userid_4],
      blocked: [],
      privacy: { profile: "public" },
      // activity: ["ACTIVITY_ID_4"],
      hiddenActivity: [],
      completion: 80,
      badges: [{ name: "Musician", earnedAt: new Date() }],
      credits: 15,
      devices: [
        {
          deviceId: "dev3",
          ip: "172.16.0.3",
          lastLogin: new Date(),
          active: true,
        },
      ],
    },
    {
      email: "alice@gmail.com",
      password: "Pass123!",
      firstName: "Alice",
      lastName: "Wong",
      username: "alicew",
      gender: "female",
      avatar: "https://randomuser.me/api/portraits/women/3.jpg",
      banner: "https://picsum.photos/800/200?3",
      bio: "Designer and artist.",
      about: "I enjoy painting and digital art.",
      skills: [skillId_1, skillId_2],
      location: { city: "San Francisco", country: "USA" },
      contact: {
        email: "alice@gmail.com",
        phone: "+14155552671",
        visibility: "private",
      },
      timeZone: "America/Los_Angeles",
      language: "en",
      followers: [userid_2],
      following: [userid_1, userid_4],
      blocked: [userid_3],
      privacy: { profile: "private" },
      // activity: ["ACTIVITY_ID_5"],
      // hiddenActivity: ["ACTIVITY_ID_6"],
      completion: 70,
      badges: [
        { name: "Artist", earnedAt: new Date() },
        { name: "Early Adopter", earnedAt: new Date() },
      ],
      credits: 20,
      devices: [
        {
          deviceId: "dev4",
          ip: "192.168.1.4",
          lastLogin: new Date(),
          active: true,
        },
      ],
    },
    {
      email: "bob@gmail.com",
      password: "Pass123!",
      firstName: "Bob",
      lastName: "Lee",
      username: "boblee",
      gender: "male",
      avatar: "https://randomuser.me/api/portraits/men/4.jpg",
      banner: "https://picsum.photos/800/200?4",
      bio: "Photographer and traveler.",
      about: "Capturing moments around the world.",
      skills: [skillId_1],
      location: { city: "Toronto", country: "Canada" },
      contact: {
        email: "bob@gmail.com",
        phone: "+14165551234",
        visibility: "public",
      },
      timeZone: "America/Toronto",
      language: "en",
      followers: ["68486cbdaa25de31a4d74a77", userid_2],
      following: [userid_3],
      blocked: [],
      privacy: { profile: "public" },
      // activity: ["ACTIVITY_ID_7"],
      hiddenActivity: [],
      completion: 60,
      badges: [{ name: "Photographer", earnedAt: new Date() }],
      credits: 8,
      devices: [
        {
          deviceId: "dev5",
          ip: "10.0.0.5",
          lastLogin: new Date(),
          active: true,
        },
      ],
    },
    // ...add more users with all fields, more badges, more devices, more relationships
  ],
  skills: [
    {
      user: userid_1,
      title: "JavaScript",
      description: "Frontend development",
      category: "Tech",
      tags: ["js", "frontend"],
      media: ["https://picsum.photos/200/200?js"],
      availability: "available",
      rating: 4.5,
      experienceLevel: "expert",
      duration: "1 hour",
    },
    {
      user: userid_1,
      title: "React",
      description: "React.js for beginners",
      category: "Tech",
      tags: ["react", "frontend"],
      media: ["https://picsum.photos/200/200?react"],
      availability: "available",
      rating: 4.7,
      experienceLevel: "expert",
      duration: "1.5 hours",
    },
    {
      user: userid_2,
      title: "Guitar",
      description: "Acoustic guitar lessons",
      category: "Music",
      tags: ["guitar", "music"],
      media: ["https://picsum.photos/200/200?guitar"],
      availability: "available",
      rating: 4.8,
      experienceLevel: "intermediate",
      duration: "45 minutes",
    },
    {
      user: userid_3,
      title: "Painting",
      description: "Watercolor basics",
      category: "Art",
      tags: ["painting", "watercolor"],
      media: ["https://picsum.photos/200/200?painting"],
      availability: "available",
      rating: 4.3,
      experienceLevel: "intermediate",
      duration: "1.5 hours",
    },
    {
      user: userid_2,
      title: "Piano",
      description: "Classical piano",
      category: "Music",
      tags: ["piano", "music"],
      media: ["https://picsum.photos/200/200?piano"],
      availability: "busy",
      rating: 4.9,
      experienceLevel: "expert",
      duration: "1 hour",
    },
    {
      user: userid_3,
      title: "Digital Art",
      description: "Digital painting basics",
      category: "Art",
      tags: ["digital", "art"],
      media: ["https://picsum.photos/200/200?digital"],
      availability: "available",
      rating: 4.6,
      experienceLevel: "intermediate",
      duration: "2 hours",
    },
    {
      user: userid_4,
      title: "Photography",
      description: "Portrait photography",
      category: "Art",
      tags: ["photo", "portrait"],
      media: ["https://picsum.photos/200/200?photo"],
      availability: "available",
      rating: 4.6,
      experienceLevel: "expert",
      duration: "1 hour",
    },
    // ...add more skills with all fields, more categories, more users
  ],
  swapRequests: [
    {
      sender: userid_1,
      receiver: userid_2,
      skill: skillId_1,
      status: "pending",
      notes: "Can we swap JavaScript for Guitar?",
    },
    {
      sender: userid_2,
      receiver: userid_3,
      skill: skillId_1,
      status: "accepted",
      notes: "Guitar for Painting swap.",
    },
    {
      sender: userid_3,
      receiver: userid_4,
      skill: skillId_1,
      status: "completed",
      notes: "Painting for Photography.",
    },
    {
      sender: userid_4,
      receiver: userid_1,
      skill: skillId_1,
      status: "rejected",
      notes: "Photography for JavaScript.",
    },
    // ...more swap requests with all statuses
  ],
  chats: [
    {
      type: "personal",
      participants: [userid_1, userid_2],
      messages: [
        {
          sender: userid_1,
          content: "Hey Jane! Ready for our swap?",
          type: "text",
          timestamp: new Date(),
        },
        {
          sender: userid_2,
          content: "Yes, let’s do it!",
          type: "text",
          timestamp: new Date(),
        },
        {
          sender: userid_1,
          content: "Here’s a file for you.",
          type: "file",
          fileUrl: "https://files.com/file1.pdf",
          timestamp: new Date(),
        },
        {
          sender: userid_2,
          content: "Thanks! I’ll check it out.",
          type: "text",
          timestamp: new Date(),
        },
      ],
      lastMessage: "Thanks! I’ll check it out.",
      readBy: [userid_2],
    },
    {
      type: "group",
      participants: [userid_1, userid_2, userid_3, userid_4],
      messages: [
        {
          sender: userid_3,
          content: "Group chat started!",
          type: "text",
          timestamp: new Date(),
        },
        {
          sender: userid_2,
          content: "Welcome everyone!",
          type: "text",
          timestamp: new Date(),
        },
        {
          sender: userid_1,
          content: "Let’s plan our next event.",
          type: "text",
          timestamp: new Date(),
        },
        {
          sender: userid_4,
          content: "I can help with the photos.",
          type: "text",
          timestamp: new Date(),
        },
      ],
      lastMessage: "I can help with the photos.",
      readBy: [userid_1, userid_2, userid_3],
    },
    // ...more chats, more messages, more types (audio, file)
  ],
  communities: [
    {
      name: "Web Dev",
      description: "Web development community",
      admin: userid_1,
      members: [userid_1, userid_2, userid_3, userid_4],
      posts: [postId_1, postId_2],
      events: [eventId_1],
      qa: [
        {
          question: "How do I deploy a React app?",
          questionAuthor: userid_1,
          tags: ["react", "deployment", "webdev"],
          upvotes: 5,
          downvotes: 0,
          voters: [],
          answers: [
            {
              user: userid_2,
              content: "Use Vercel or Netlify for easy deployment.",
              upvotes: 3,
              downvotes: 0,
              voters: [],
              isAccepted: false,
              createdAt: new Date(),
            },
            {
              user: userid_3,
              content: "GitHub Pages works too and it's free.",
              upvotes: 1,
              downvotes: 0,
              voters: [],
              isAccepted: false,
              createdAt: new Date(),
            },
          ],
          isResolved: false,
          createdAt: new Date(),
        },
        {
          question: "What's the best CSS framework for beginners?",
          questionAuthor: userid_2,
          tags: ["css", "framework", "beginners"],
          upvotes: 8,
          downvotes: 1,
          voters: [],
          answers: [
            { 
              user: userid_1, 
              content: "Tailwind CSS is great for rapid development!", 
              upvotes: 5,
              downvotes: 0,
              voters: [],
              isAccepted: true,
              createdAt: new Date(),
            },
          ],
          isResolved: true,
          createdAt: new Date(),
        },
        {
          question: "How to handle state management in large React apps?",
          questionAuthor: userid_3,
          tags: ["react", "state-management", "redux"],
          upvotes: 12,
          downvotes: 2,
          voters: [],
          answers: [
            {
              user: userid_1,
              content: "Redux Toolkit is the modern way to go.",
              upvotes: 7,
              downvotes: 0,
              voters: [],
              isAccepted: false,
              createdAt: new Date(),
            },
            {
              user: userid_4,
              content: "Zustand is also a great lightweight alternative.",
              upvotes: 4,
              downvotes: 1,
              voters: [],
              isAccepted: false,
              createdAt: new Date(),
            },
          ],
          isResolved: false,
          createdAt: new Date(),
        },
      ],
      debates: [
        {
          topic: "Frontend vs Backend",
          comments: [
            {
              user: userid_1,
              content: "Frontend is more creative.",
              vote: "agree",
            },
            {
              user: userid_3,
              content: "Backend is more powerful.",
              vote: "disagree",
            },
          ],
        },
        {
          topic: "Remote vs Onsite",
          comments: [
            {
              user: userid_2,
              content: "Remote is more flexible.",
              vote: "agree",
            },
          ],
        },
      ],
      rules: "Be respectful. No spam. Help others.",
      joinRule: "open",
    },
    // ...more communities, more Q&A, more debates
  ],
  posts: [
    {
      title: "Welcome to Web Dev!",
      community: communityId_1,
      user: userid_1,
      content: "Let’s share web dev tips!",
      media: ["https://picsum.photos/300/200?post1"],
      tags: ["webdev", "tips"],
      visibility: "public",
      likes: [userid_2, userid_3],
      comments: [
        {
          user: userid_2,
          content: "Great post!",
          replies: [
            { user: userid_1, content: "Thanks!" },
            { user: userid_3, content: "Agreed!" },
          ],
        },
        {
          user: userid_3,
          content: "What’s your favorite framework?",
          replies: [],
        },
      ],
      pinned: true,
      flagged: false,
    },
    {
      title: "Show us your art!",
      community: communityId_2,
      user: userid_3,
      content: "Share your latest paintings.",
      media: ["https://picsum.photos/300/200?post2"],
      tags: ["art", "painting"],
      visibility: "public",
      likes: [userid_1],
      comments: [
        {
          user: userid_1,
          content: "Beautiful work!",
          replies: [{ user: userid_3, content: "Thank you!" }],
        },
      ],
      pinned: false,
      flagged: false,
    },
    // ...more posts, more comments, more replies
  ],
  events: [
    {
      community: communityId_1,
      title: "Web Dev Meetup",
      description: "Monthly meetup",
      date: new Date(),
      location: "Online",
      virtual: true,
      virtualLink: "https://zegocloud.com/meetup1",
      rsvp: [userid_2, userid_3, userid_4],
    },
    {
      community: communityId_2,
      title: "Art Expo",
      description: "Annual art exhibition",
      date: new Date(),
      location: "Gallery",
      virtual: false,
      virtualLink: "",
      rsvp: [userid_1, userid_3],
    },
    // ...more events, more rsvps
  ],
  notifications: [
    {
      user: userid_1,
      type: "swap_request",
      sender: userid_2,
      context: "Swap: JavaScript for Guitar",
      read: false,
      action: "View Swap",
    },
    {
      user: userid_2,
      type: "comment",
      sender: userid_1,
      context: "Post: Welcome to Web Dev!",
      read: true,
      action: "View Post",
    },
    {
      user: userid_3,
      type: "like",
      sender: userid_4,
      context: "Post: Show us your art!",
      read: false,
      action: "View Post",
    },
    {
      user: userid_4,
      type: "event_invite",
      sender: userid_1,
      context: "Event: Web Dev Meetup",
      read: false,
      action: "RSVP",
    },
    // ...more notifications, more types
  ],
  activities: [
    {
      user: userid_1,
      type: "login",
      refId: null,
      details: "User logged in",
    },
    {
      user: userid_2,
      type: "post",
      refId: postId_1,
      details: "Created a new post",
    },
    {
      user: userid_3,
      type: "swap",
      refId: "SWAP_ID_1",
      details: "Requested a swap",
    },
    {
      user: userid_4,
      type: "event",
      refId: eventId_1,
      details: "Joined an event",
    },
    // ...more activities, more types
  ],
  transactions: [
    {
      user: userid_1,
      type: "premium_skill",
      amount: 10,
      status: "completed",
      stripeId: "stripe_123",
    },
    {
      user: userid_2,
      type: "tip",
      amount: 5,
      status: "pending",
      stripeId: "stripe_456",
    },
    {
      user: userid_3,
      type: "premium_skill",
      amount: 15,
      status: "failed",
      stripeId: "stripe_789",
    },
    // ...more transactions, more types, more statuses
  ],
  savedSearches: [
    {
      user: userid_1,
      query: "JavaScript",
      filters: { category: "Tech", location: "USA", rating: 4 },
      name: "JS in USA",
    },
    {
      user: userid_2,
      query: "Guitar",
      filters: { category: "Music", location: "UK", rating: 5 },
      name: "Guitar UK",
    },
    {
      user: userid_3,
      query: "Painting",
      filters: { category: "Art", location: "USA", rating: 5 },
      name: "Painting USA",
    },
    // ...more saved searches, more filters
  ],
  swapCards: [
    {
      user: userid_1,
      offeredSkill: skillId_1,
      desiredSkill: skillId_1,
      description: "Swap JavaScript for Guitar lessons",
      status: "open",
      tags: ["js", "guitar"],
      location: { city: "New York", country: "USA" },
      availableTimes: [
        { day: "Monday", from: "10:00", to: "12:00" },
        { day: "Wednesday", from: "14:00", to: "16:00" },
      ],
      images: [
        "https://picsum.photos/200/200?swapcard1",
        "https://picsum.photos/200/200?swapcard2",
      ],
      likes: [userid_2, userid_3],
      views: 25,
      isFeatured: true,
      expiryDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
      extraData: { note: "Flexible with time.", urgency: "high" },
    },
    {
      user: userid_2,
      offeredSkill: skillId_1,
      desiredSkill: skillId_1,
      description: "Guitar for Painting swap",
      status: "matched",
      tags: ["guitar", "painting"],
      location: { city: "London", country: "UK" },
      availableTimes: [{ day: "Friday", from: "09:00", to: "11:00" }],
      images: ["https://picsum.photos/200/200?swapcard3"],
      likes: [userid_1],
      views: 10,
      isFeatured: false,
      expiryDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
      extraData: { note: "Prefer mornings." },
    },
    // ...more swap cards, more users, more skills, more tags
  ],
};
